apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  # name: argocd-success-rate
  name: {{ include "argocd.fullname" . }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  args:
  - name: service-name
  metrics:
  - name: {{ include "argocd.fullname" . }}-success-rate
    interval: 30s
    count: 6    
    successCondition: result[0] >= 0.85
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        insecure: true
        # timeout is expressed in seconds
        timeout: 600
        headers:
        - key: X-Scope-OrgID
          value: '1'
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{ include "argocd.fullname" . }}-canary.default.svc.cluster.local",response_code=~"2.*"}[2m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{ include "argocd.fullname" . }}-canary.default.svc.cluster.local"}[2m]
          ))

# kubectl argo rollouts get rollout argocd --watch
# kubectl argo rollouts dashboard