apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "argocd.fullname" . }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: {{ include "argocd.fullname" . }}-canary
      stableService: {{ include "argocd.fullname" . }}-stable
      trafficRouting:
        istio:
          virtualServices:
          - name: {{ include "argocd.fullname" . }}          
    {{- if .Values.rollout.steps }}      
    {{- with .Values.rollout.steps }}      
      steps:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- else }}
      steps:
      - setWeight: 50
      - pause: {duration: 1m}
      - analysis:
          templates:
            - templateName: {{ include "argocd.fullname" . }}
          args:
          - name: service-name
            value: {{ include "argocd.fullname" . }}-canary.default.svc.cluster.local
      - setWeight: 100
    {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "argocd.selectorLabels" .  | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "argocd.selectorLabels" .  | nindent 8}}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}

           