name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-test    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: echo github.actor
      run: |
        echo ${{ github.actor }}            

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}    


    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: "{{defaultContext}}"
        push: ${{ github.event_name != 'pull_request' }}
        target: production
        tags: macabrabits/argocd-test:${{github.run_number}}
        labels: ${{ steps.meta.outputs.labels }}
        # cache-from: type=gha
        # cache-to: type=gha,mode=max

    - uses: actions/checkout@v2
    
    - name: update image tag
      run: |
        sed -i 's/tag: \"[0-9a-z]*\"$/tag: \"${{github.run_number}}\"/g' ${{ github.workspace }}/helmchart/values.yaml
        cat ${{ github.workspace }}/helmchart/values.yaml


    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Deploy Action"
        git commit -am "update image tag"

    - name: echo something
      run: |
        echo ${{ github.ref }}  
    
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
              
